In [1]:
import os 
import polars as pl 
from utils.utils import *

In [2]:
duration = calculate_metcrics_for_94min()
duration.head(1)

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Date      ┆ Abs HSR(m ┆ Accelerat ┆ … ┆ HSR Rel   ┆ Sprint    ┆ Sprint    ┆ Total    │
│ ---       ┆ ---       ┆ )_94min   ┆ ions_94mi ┆   ┆ (m)_94min ┆ Abs       ┆ Rel       ┆ impacts_ │
│ str       ┆ str       ┆ ---       ┆ n         ┆   ┆ ---       ┆ (m)_94min ┆ (m)_94min ┆ 94min    │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Nacho     ┆ 27/08/202 ┆ 854.90425 ┆ 2570.1510 ┆ … ┆ 183.33322 ┆ 257.82246 ┆ 0.0       ┆ 22264.63 │
│ Méndez    ┆ 3         ┆ 4         ┆ 99        ┆   ┆ 5         ┆ 1         ┆           ┆ 5989     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
calculate_percentage_difference_vs_reference("30/11/2023")

shape: (22, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Abs HSR(m ┆ Accelerat ┆ Decelerat ┆ … ┆ HSR Rel   ┆ Sprint    ┆ Sprint    ┆ Total    │
│ ---       ┆ )_diff_pc ┆ ions_diff ┆ ions_diff ┆   ┆ (m)_diff_ ┆ Abs (m)_d ┆ Rel (m)_d ┆ impacts_ │
│ str       ┆ t         ┆ _pct      ┆ _pct      ┆   ┆ pct       ┆ iff_pct   ┆ iff_pct   ┆ diff_pct │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Nacho     ┆ -100.0    ┆ -48.42    ┆ -48.17    ┆ … ┆ -100.0    ┆ -100.0    ┆ NaN       ┆ -86.77   │
│ Martín    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Jonathan  ┆ -88.33    ┆ -54.01    ┆ -53.54    ┆ … ┆ -93.0     ┆ -89.85    ┆ NaN       ┆ -87.73   │
│ Varane    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Enol Coto ┆ -100.0    ┆ -51.52    ┆ -50.68    ┆ … ┆ -100.0    ┆ -100.0    ┆ NaN       ┆ -87.94   │
│ Cali Izqu ┆ -100.0    ┆ -51.21    ┆ -51.58    ┆ … ┆ -100.0    ┆ -100.0    ┆ NaN       ┆ -81.32   │
│ ierdoz    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ José      ┆ -95.03    ┆ -47.59    ┆ -47.49    ┆ … ┆ -92.01    ┆ -91.67    ┆ NaN       ┆ -81.42   │
│ Ángel     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Valdés    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Alexandru ┆ -91.83    ┆ -53.29    ┆ -53.29    ┆ … ┆ -93.02    ┆ -87.51    ┆ -100.0    ┆ -83.35   │
│ Pascanu   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Roberto   ┆ -100.0    ┆ -53.97    ┆ -54.02    ┆ … ┆ -100.0    ┆ -100.0    ┆ NaN       ┆ -87.91   │
│ Suárez    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Pier      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Víctor    ┆ -100.0    ┆ -33.38    ┆ -33.14    ┆ … ┆ -100.0    ┆ -100.0    ┆ NaN       ┆ -80.5    │
│ Campuzano ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Pablo     ┆ -100.0    ┆ -52.57    ┆ -52.57    ┆ … ┆ -100.0    ┆ -100.0    ┆ NaN       ┆ -88.76   │
│ Insua     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Fran      ┆ -96.69    ┆ -32.14    ┆ -31.06    ┆ … ┆ -100.0    ┆ -100.0    ┆ NaN       ┆ -75.77   │
│ Villalba  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
get_players_data("30/11/2023")

shape: (23, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Position  ┆ Abs       ┆ Abs HSR(m ┆ … ┆ Sprint    ┆ Sprint    ┆ Step      ┆ Total    │
│ ---       ┆ ---       ┆ HSR(m)    ┆ )/Min     ┆   ┆ Abs (m)   ┆ Rel (m)   ┆ Balance   ┆ impacts  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ (%)       ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Nacho     ┆ Centrocam ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.008145  ┆ 2668.0   │
│ Martín    ┆ pista     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Jonathan  ┆ Central   ┆ 51.963033 ┆ 1.059821  ┆ … ┆ 21.527608 ┆ 0.0       ┆ -0.002302 ┆ 2641.0   │
│ Varane    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Enol Coto ┆ Lateral   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.018992 ┆ 2571.0   │
│ Cali Izqu ┆ Central   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.022102  ┆ 2991.0   │
│ ierdoz    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ José      ┆ Lateral   ┆ 26.971403 ┆ 0.5501    ┆ … ┆ 16.036079 ┆ 0.0       ┆ 0.001373  ┆ 3276.0   │
│ Ángel     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Valdés    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Axel      ┆ Central   ┆ 16.002488 ┆ 0.326382  ┆ … ┆ 12.272763 ┆ 0.0       ┆ -0.039846 ┆ 3079.0   │
│ Bamba     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Roberto   ┆ Central   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.050158 ┆ 2426.0   │
│ Suárez    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Pier      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Víctor    ┆ Delantero ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.026715 ┆ 3761.0   │
│ Campuzano ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Pablo     ┆ Central   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.00708  ┆ 2023.0   │
│ Insua     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Fran      ┆ Extremo   ┆ 22.731446 ┆ 0.463623  ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.039317 ┆ 4175.0   │
│ Villalba  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘