In [2]:
import os 
import polars as pl 
from utils.utils import *

In [10]:
duration = calculate_player_statistics_94min()
duration.head(10)

shape: (10, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ estadisti ┆ Distance  ┆ Speed     ┆ … ┆ Decelerat ┆ Dif. ACC/ ┆ Step      ┆ Total    │
│ ---       ┆ ca        ┆ (m)_94min ┆ Zones (m) ┆   ┆ ions_94mi ┆ DEC_94min ┆ Balance   ┆ impacts_ │
│ str       ┆ ---       ┆ ---       ┆ [0.0,     ┆   ┆ n         ┆ ---       ┆ (%)_94min ┆ 94min    │
│           ┆ str       ┆ f64       ┆ 6.0]km/h… ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Alexandru ┆ max       ┆ 10916.740 ┆ 4197.0952 ┆ … ┆ 2985.4882 ┆ 20.749164 ┆ 0.015587  ┆ 26254.73 │
│ Pascanu   ┆           ┆ 143       ┆ 38        ┆   ┆ 39        ┆           ┆           ┆ 6842     │
│ Alexandru ┆ mean      ┆ 10075.126 ┆ 3516.1262 ┆ … ┆ 2784.4126 ┆ -12.03897 ┆ -0.005555 ┆ 24224.94 │
│ Pascanu   ┆           ┆ 753       ┆ 36        ┆   ┆           ┆           ┆           ┆ 5661     │
│ Alexandru ┆ median    ┆ 10131.137 ┆ 3330.8239 ┆ … ┆ 2816.1593 ┆ -10.71988 ┆ -0.005026 ┆ 24276.52 │
│ Pascanu   ┆           ┆ 98        ┆ 35        ┆   ┆ 46        ┆ 6         ┆           ┆ 1739     │
│ Alexandru ┆ min       ┆ 9218.6491 ┆ 3072.3147 ┆ … ┆ 2418.1771 ┆ -34.73684 ┆ -0.021623 ┆ 21635.40 │
│ Pascanu   ┆           ┆ 92        ┆           ┆   ┆ 5         ┆ 2         ┆           ┆ 9836     │
│ Alexandru ┆ p75       ┆ 10297.759 ┆ 3797.8638 ┆ … ┆ 2840.8888 ┆ -7.681307 ┆ 0.003967  ┆ 25125.57 │
│ Pascanu   ┆           ┆ 062       ┆ 66        ┆   ┆ 89        ┆           ┆           ┆ 4841     │
│ Alexandru ┆ p90       ┆ 10379.083 ┆ 4025.0745 ┆ … ┆ 2964.6289 ┆ 4.846194  ┆ 0.009362  ┆ 26081.40 │
│ Pascanu   ┆           ┆ 428       ┆ 57        ┆   ┆ 69        ┆           ┆           ┆ 2469     │
│ Alexandru ┆ p99       ┆ 10916.740 ┆ 4197.0952 ┆ … ┆ 2985.4882 ┆ 20.749164 ┆ 0.015587  ┆ 26254.73 │
│ Pascanu   ┆           ┆ 143       ┆ 38        ┆   ┆ 39        ┆           ┆           ┆ 6842     │
│ Cali Izqu ┆ max       ┆ 9904.1366 ┆ 5146.3095 ┆ … ┆ 2897.7991 ┆ 5.815432  ┆ 0.045811  ┆ 16688.78 │
│ ierdoz    ┆           ┆ 72        ┆ 26        ┆   ┆ 32        ┆           ┆           ┆ 1975     │
│ Cali Izqu ┆ mean      ┆ 9349.5859 ┆ 3766.9741 ┆ … ┆ 2749.0179 ┆ -7.521073 ┆ 0.016425  ┆ 15856.53 │
│ ierdoz    ┆           ┆ 35        ┆ 93        ┆   ┆ 2         ┆           ┆           ┆ 7969     │
│ Cali Izqu ┆ median    ┆ 9405.2226 ┆ 3618.1768 ┆ … ┆ 2776.6353 ┆ -8.330253 ┆ 0.01621   ┆ 15918.20 │
│ ierdoz    ┆           ┆ 08        ┆ 57        ┆   ┆ 75        ┆           ┆           ┆ 3032     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
duration = calculate_player_statistics_94min()
jugador = "Christian Rivera"
filtrado = duration.filter(duration["Player"] == jugador)
filtrado.head(10)

shape: (7, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ estadisti ┆ Distance  ┆ Speed     ┆ … ┆ Decelerat ┆ Dif. ACC/ ┆ Step      ┆ Total    │
│ ---       ┆ ca        ┆ (m)_94min ┆ Zones (m) ┆   ┆ ions_94mi ┆ DEC_94min ┆ Balance   ┆ impacts_ │
│ str       ┆ ---       ┆ ---       ┆ [0.0,     ┆   ┆ n         ┆ ---       ┆ (%)_94min ┆ 94min    │
│           ┆ str       ┆ f64       ┆ 6.0]km/h… ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Christian ┆ max       ┆ 11615.784 ┆ 4318.5483 ┆ … ┆ 2627.4775 ┆ 13.469388 ┆ 0.033525  ┆ 20757.85 │
│ Rivera    ┆           ┆ 79        ┆ 2         ┆   ┆ 54        ┆           ┆           ┆ 5275     │
│ Christian ┆ mean      ┆ 10491.248 ┆ 3588.7562 ┆ … ┆ 2461.9340 ┆ -11.78913 ┆ -0.000239 ┆ 19468.80 │
│ Rivera    ┆           ┆ 296       ┆ 75        ┆   ┆ 05        ┆ 8         ┆           ┆ 9161     │
│ Christian ┆ median    ┆ 10443.463 ┆ 3465.2405 ┆ … ┆ 2487.7387 ┆ -13.50089 ┆ -0.003381 ┆ 18994.66 │
│ Rivera    ┆           ┆ 418       ┆ 14        ┆   ┆ 76        ┆ 8         ┆           ┆ 6667     │
│ Christian ┆ min       ┆ 9609.4969 ┆ 3128.8778 ┆ … ┆ 2025.8761 ┆ -41.43673 ┆ -0.021335 ┆ 18513.68 │
│ Rivera    ┆           ┆ 87        ┆ 44        ┆   ┆ 99        ┆ 5         ┆           ┆ 4567     │
│ Christian ┆ p75       ┆ 10768.173 ┆ 4072.4623 ┆ … ┆ 2602.2980 ┆ 0.0       ┆ 0.007841  ┆ 20520.0  │
│ Rivera    ┆           ┆ 117       ┆ 21        ┆   ┆ 25        ┆           ┆           ┆          │
│ Christian ┆ p90       ┆ 10768.173 ┆ 4072.4623 ┆ … ┆ 2602.2980 ┆ 0.0       ┆ 0.007841  ┆ 20520.0  │
│ Rivera    ┆           ┆ 117       ┆ 21        ┆   ┆ 25        ┆           ┆           ┆          │
│ Christian ┆ p99       ┆ 11615.784 ┆ 4318.5483 ┆ … ┆ 2627.4775 ┆ 13.469388 ┆ 0.033525  ┆ 20757.85 │
│ Rivera    ┆           ┆ 79        ┆ 2         ┆   ┆ 54        ┆           ┆           ┆ 5275     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
calculate_percentage_difference_vs_reference("30/11/2023")

Error al calcular diferencias porcentuales: Rel HSR(m)

shape: (0, 0)
┌┐
╞╡
└┘

In [4]:
get_players_data("30/11/2023")

shape: (23, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Position  ┆ Abs       ┆ Abs HSR(m ┆ … ┆ Sprint    ┆ Sprint    ┆ Step      ┆ Total    │
│ ---       ┆ ---       ┆ HSR(m)    ┆ )/Min     ┆   ┆ Abs (m)   ┆ Rel (m)   ┆ Balance   ┆ impacts  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ (%)       ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Nacho     ┆ Centrocam ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.008145  ┆ 2668.0   │
│ Martín    ┆ pista     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Jonathan  ┆ Central   ┆ 51.963033 ┆ 1.059821  ┆ … ┆ 21.527608 ┆ 0.0       ┆ -0.002302 ┆ 2641.0   │
│ Varane    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Enol Coto ┆ Lateral   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.018992 ┆ 2571.0   │
│ Cali Izqu ┆ Central   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.022102  ┆ 2991.0   │
│ ierdoz    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ José      ┆ Lateral   ┆ 26.971403 ┆ 0.5501    ┆ … ┆ 16.036079 ┆ 0.0       ┆ 0.001373  ┆ 3276.0   │
│ Ángel     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Valdés    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Axel      ┆ Central   ┆ 16.002488 ┆ 0.326382  ┆ … ┆ 12.272763 ┆ 0.0       ┆ -0.039846 ┆ 3079.0   │
│ Bamba     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Roberto   ┆ Central   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.050158 ┆ 2426.0   │
│ Suárez    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Pier      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Víctor    ┆ Delantero ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.026715 ┆ 3761.0   │
│ Campuzano ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Pablo     ┆ Central   ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.00708  ┆ 2023.0   │
│ Insua     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Fran      ┆ Extremo   ┆ 22.731446 ┆ 0.463623  ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.039317 ┆ 4175.0   │
│ Villalba  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
calculate_player_statistics_94min()

ColumnNotFoundError: Rel HSR(m)