In [1]:
import os 
import polars as pl 
from utils.utils import *

In [2]:
temp = calculate_metrics_for_94min()
temp

DataFrames salvos em c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed\references:
- Histórico completo: metrics_94min_historical.parquet (119 registros)
- Últimos 4 jogos: metrics_94min_last_4_games.parquet (38 registros)

shape: (119, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Position  ┆ Date      ┆ Total     ┆ … ┆ Decelerat ┆ Dif. ACC/ ┆ Step      ┆ Total    │
│ ---       ┆ ---       ┆ ---       ┆ Minutes   ┆   ┆ ions_94mi ┆ DEC_94min ┆ Balance   ┆ impacts_ │
│ str       ┆ str       ┆ str       ┆ en        ┆   ┆ n         ┆ ---       ┆ (%)_94min ┆ 94min    │
│           ┆           ┆           ┆ Partido   ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Gaspar    ┆ Extremo   ┆ 27/11/202 ┆ 74.766667 ┆ … ┆ 2753.3660 ┆ -26.40214 ┆ 0.021681  ┆ 26162.00 │
│ Campos    ┆           ┆ 3         ┆           ┆   ┆ 28        ┆           ┆           ┆ 6242     │
│ Juan      ┆ Extremo   ┆ 27/11/202 ┆ 83.166667 ┆ … ┆ 2783.8316 ┆ 19.214429 ┆ 0.00512   ┆ 18734.06 │
│ Otero     ┆           ┆ 3         ┆           ┆   ┆ 63        ┆           ┆           ┆ 8136     │
│ Uros Djur ┆ Delantero ┆ 27/11/202 ┆ 92.5      ┆ … ┆ 2731.5891 ┆ -2.032432 ┆ 0.029853  ┆ 20354.81 │
│ djevic    ┆           ┆ 3         ┆           ┆   ┆ 89        ┆           ┆           ┆ 0811     │
│ Nacho     ┆ Centrocam ┆ 27/11/202 ┆ 92.5      ┆ … ┆ 2684.8432 ┆ 20.324324 ┆ 0.048689  ┆ 23290.65 │
│ Méndez    ┆ pista     ┆ 3         ┆           ┆   ┆ 43        ┆           ┆           ┆ 9459     │
│ José      ┆ Lateral   ┆ 27/11/202 ┆ 92.5      ┆ … ┆ 2718.3783 ┆ -6.097297 ┆ -0.003627 ┆ 18243.11 │
│ Ángel     ┆           ┆ 3         ┆           ┆   ┆ 78        ┆           ┆           ┆ 3514     │
│ Valdés    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Diego     ┆ Lateral   ┆ 01/11/202 ┆ 94.633333 ┆ … ┆ 2646.1711 ┆ -16.88622 ┆ 0.027461  ┆ 20492.92 │
│ Sánchez   ┆           ┆ 3         ┆           ┆   ┆ 87        ┆ 8         ┆           ┆ 7087     │
│ Guille    ┆ Lateral   ┆ 01/11/202 ┆ 64.283333 ┆ … ┆ 2575.0687 ┆ -42.40601 ┆ 0.06388   ┆ 19411.71 │
│ Rosas     ┆           ┆ 3         ┆           ┆   ┆ 06        ┆ 5         ┆           ┆ 8953     │
│ Ignacio   ┆ Delantero ┆ 01/11/202 ┆ 94.633333 ┆ … ┆ 2706.7629 ┆ -25.82599 ┆ 0.008306  ┆ 7867.988 │
│ Jeraldino ┆           ┆ 3         ┆           ┆   ┆ 45        ┆ 5         ┆           ┆ 728      │
│ Cali Izqu ┆ Central   ┆ 01/11/202 ┆ 94.633333 ┆ … ┆ 2794.1740 ┆ -8.939768 ┆ 0.017877  ┆ 15804.51 │
│ ierdoz    ┆           ┆ 3         ┆           ┆   ┆ 05        ┆           ┆           ┆ 5675     │
│ Uros Djur ┆ Delantero ┆ 01/11/202 ┆ 75.55     ┆ … ┆ 2773.3421 ┆ 1.244209  ┆ 0.007541  ┆ 17447.54 │
│ djevic    ┆           ┆ 3         ┆           ┆   ┆ 58        ┆           ┆           ┆ 4672     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
reference = calculate_percentage_difference_vs_reference("30/11/2023")

DataFrames salvos em c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed\references:
- Histórico completo: metrics_94min_historical.parquet (119 registros)
- Últimos 4 jogos: metrics_94min_last_4_games.parquet (38 registros)
DataFrames salvos em c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed\references:
- Histórico completo: metrics_94min_historical.parquet (119 registros)
- Últimos 4 jogos: metrics_94min_last_4_games.parquet (38 registros)
Error al calcular estadísticas: unable to find column "Total Distance (m)"; valid columns: ["Player", "Position", "Date", "Total Minutes en Partido", "Distance (m)_94min", "Speed Zones (m) [0.0, 6.0]km/h (m)_94min", "Abs HSR(m)_94min", "HSR Rel (m)_94min", "Sprint Abs (m)_94min", "Sprint Rel (m)_94min", "Explosive Dist (m)_94min", "MAX Speed(km/h)_94min", "Max Acceleration_94min", "Accelerations_94min", "Decelerations_94min", "Dif. ACC/DEC_94min", "Step Balance (%)_94min", "Total impacts_94min"]

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
DF ["Player", "Position", "Date", "Total Minutes en Partido", ...]; PROJECT */18 COLUMNS
No se pudieron obtener estadísticas de referencia.

In [4]:
reference

shape: (0, 0)
┌┐
╞╡
└┘

In [5]:
data =get_players_data("06/12/2023")
data

shape: (15, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Position  ┆ Abs       ┆ Abs HSR(m ┆ … ┆ Sprint    ┆ Sprint    ┆ Step      ┆ Total    │
│ ---       ┆ ---       ┆ HSR(m)    ┆ )/Min     ┆   ┆ Abs (m)   ┆ Rel (m)   ┆ Balance   ┆ impacts  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ (%)       ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Jonathan  ┆ Central   ┆ 360.29077 ┆ 3.006683  ┆ … ┆ 192.03299 ┆ 0.0       ┆ -0.004431 ┆ 25969.0  │
│ Varane    ┆           ┆ 4         ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ Jordan    ┆ Centrocam ┆ 280.55985 ┆ 2.341316  ┆ … ┆ 115.20664 ┆ 0.0       ┆ -0.016087 ┆ 14420.0  │
│ Carrillo  ┆ pista     ┆ 9         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ Enol Coto ┆ Lateral   ┆ 520.99103 ┆ 4.347751  ┆ … ┆ 213.56135 ┆ 0.0       ┆ 0.004139  ┆ 16280.0  │
│           ┆           ┆ 3         ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ Pablo     ┆ Lateral   ┆ 476.53358 ┆ 3.976747  ┆ … ┆ 111.38248 ┆ 0.0       ┆ -0.000046 ┆ 22493.0  │
│ García    ┆           ┆ 8         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ Diego     ┆ Lateral   ┆ 708.94437 ┆ 5.916251  ┆ … ┆ 312.18879 ┆ 0.0       ┆ 0.003056  ┆ 24136.0  │
│ Sánchez   ┆           ┆ 7         ┆           ┆   ┆ 2         ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Juan      ┆ Extremo   ┆ 338.31912 ┆ 2.823326  ┆ … ┆ 195.24323 ┆ 0.0       ┆ 0.024577  ┆ 6570.0   │
│ Otero     ┆           ┆ 6         ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ Pablo     ┆ Central   ┆ 359.98081 ┆ 3.004096  ┆ … ┆ 145.65877 ┆ 0.0       ┆ -0.021996 ┆ 22754.0  │
│ Insua     ┆           ┆ 4         ┆           ┆   ┆ 1         ┆           ┆           ┆          │
│ Ignacio   ┆ Delantero ┆ 132.5523  ┆ 1.10617   ┆ … ┆ 47.323253 ┆ 9.342283  ┆ 0.015035  ┆ 7105.0   │
│ Jeraldino ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Fran      ┆ Extremo   ┆ 771.86909 ┆ 6.441368  ┆ … ┆ 266.32358 ┆ 11.781539 ┆ 0.034057  ┆ 21511.0  │
│ Villalba  ┆           ┆ 6         ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ Uros Djur ┆ Delantero ┆ 413.65022 ┆ 3.451975  ┆ … ┆ 190.63301 ┆ 0.0       ┆ 0.047012  ┆ 12840.0  │
│ djevic    ┆           ┆ 4         ┆           ┆   ┆ 4         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
teste = calculate_player_statistics_94min()

teste

DataFrames salvos em c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed\references:
- Histórico completo: metrics_94min_historical.parquet (119 registros)
- Últimos 4 jogos: metrics_94min_last_4_games.parquet (38 registros)
DataFrames salvos em c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed\references:
- Histórico completo: metrics_94min_historical.parquet (119 registros)
- Últimos 4 jogos: metrics_94min_last_4_games.parquet (38 registros)
Error al calcular estadísticas: unable to find column "Total Distance (m)"; valid columns: ["Player", "Position", "Date", "Total Minutes en Partido", "Distance (m)_94min", "Speed Zones (m) [0.0, 6.0]km/h (m)_94min", "Abs HSR(m)_94min", "HSR Rel (m)_94min", "Sprint Abs (m)_94min", "Sprint Rel (m)_94min", "Explosive Dist (m)_94min", "MAX Speed(km/h)_94min", "Max Acceleration_94min", "Accelerations_94min", "Decelerations_94min", "Dif. ACC/DEC_94min", "Step Balance (%)_94min", "Total impacts_94min"]

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
DF ["Player", "Position", "Date", "Total Minutes en Partido", ...]; PROJECT */18 COLUMNS

shape: (0, 0)
┌┐
╞╡
└┘

In [10]:
teste = calculate_player_statistics_94min()

teste

DataFrames salvos em c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed\references:
- Histórico completo: metrics_94min_historical.parquet (119 registros)
- Últimos 4 jogos: metrics_94min_last_4_games.parquet (38 registros)
DataFrames salvos em c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed\references:
- Histórico completo: metrics_94min_historical.parquet (119 registros)
- Últimos 4 jogos: metrics_94min_last_4_games.parquet (38 registros)
Error al calcular estadísticas: unable to find column "Total Distance (m)"; valid columns: ["Player", "Position", "Date", "Total Minutes en Partido", "Distance (m)_94min", "Speed Zones (m) [0.0, 6.0]km/h (m)_94min", "Abs HSR(m)_94min", "HSR Rel (m)_94min", "Sprint Abs (m)_94min", "Sprint Rel (m)_94min", "Explosive Dist (m)_94min", "MAX Speed(km/h)_94min", "Max Acceleration_94min", "Accelerations_94min", "Decelerations_94min", "Dif. ACC/DEC_94min", "Step Balance (%)_94min", "Total impacts_94min"]

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
DF ["Player", "Position", "Date", "Total Minutes en Partido", ...]; PROJECT */18 COLUMNS

shape: (0, 0)
┌┐
╞╡
└┘

In [11]:
# import parquet df in data/processed/references
import polars as pl

df = pl.read_parquet('data/processed/references/estadisticas_matchday.parquet')
df

shape: (2_387, 23)
┌────────┬──────────┬───────────┬──────────────┬───┬─────────────┬─────────┬─────────┬─────────────┐
│ Player ┆ Position ┆ Match Day ┆ Estadistica  ┆ … ┆ Step        ┆ Total   ┆ tipo    ┆ Team        │
│ ---    ┆ ---      ┆ ---       ┆ ---          ┆   ┆ Balance (%) ┆ impacts ┆ ---     ┆ ---         │
│ str    ┆ str      ┆ str       ┆ str          ┆   ┆ ---         ┆ ---     ┆ str     ┆ str         │
│        ┆          ┆           ┆              ┆   ┆ f64         ┆ f64     ┆         ┆             │
╞════════╪══════════╪═══════════╪══════════════╪═══╪═════════════╪═════════╪═════════╪═════════════╡
│ Guille ┆ Lateral  ┆ -2 MD     ┆ mean         ┆ … ┆ 0.014793    ┆ 5786.8  ┆ jugador ┆ null        │
│ Rosas  ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆             │
│ Guille ┆ Lateral  ┆ -2 MD     ┆ median       ┆ … ┆ 0.010694    ┆ 5942.5  ┆ jugador ┆ null        │
│ Rosas  ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆             │
│ Guille ┆ Lateral  ┆ -2 MD     ┆ max          ┆ … ┆ 0.093714    ┆ 7603.0  ┆ jugador ┆ null        │
│ Rosas  ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆             │
│ Guille ┆ Lateral  ┆ -2 MD     ┆ min          ┆ … ┆ -0.020031   ┆ 2972.0  ┆ jugador ┆ null        │
│ Rosas  ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆             │
│ Guille ┆ Lateral  ┆ -2 MD     ┆ p75          ┆ … ┆ 0.032786    ┆ 6564.0  ┆ jugador ┆ null        │
│ Rosas  ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆             │
│ …      ┆ …        ┆ …         ┆ …            ┆ … ┆ …           ┆ …       ┆ …       ┆ …           │
│ null   ┆ null     ┆ +1 MD     ┆ max          ┆ … ┆ 0.063142    ┆ 13736.0 ┆ equipo  ┆ Sporting de │
│        ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆ Gijón       │
│ null   ┆ null     ┆ +1 MD     ┆ min          ┆ … ┆ -0.044072   ┆ 3641.0  ┆ equipo  ┆ Sporting de │
│        ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆ Gijón       │
│ null   ┆ null     ┆ +1 MD     ┆ p75          ┆ … ┆ 0.015584    ┆ 10393.0 ┆ equipo  ┆ Sporting de │
│        ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆ Gijón       │
│ null   ┆ null     ┆ +1 MD     ┆ p90          ┆ … ┆ 0.027323    ┆ 11772.0 ┆ equipo  ┆ Sporting de │
│        ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆ Gijón       │
│ null   ┆ null     ┆ +1 MD     ┆ p95          ┆ … ┆ 0.031479    ┆ 12146.0 ┆ equipo  ┆ Sporting de │
│        ┆          ┆           ┆              ┆   ┆             ┆         ┆         ┆ Gijón       │
└────────┴──────────┴───────────┴──────────────┴───┴─────────────┴─────────┴─────────┴─────────────┘